--day02
--테이블 생성하기 (제약조건 없는 테이블 - 일반적인 형태)
--요구사항
--학번, 이름, 주민번호를 갖고 있는 테이블 TEST01을 생성해보자
--숫자 가변형 고정형

CREATE TABLE TEST01(
		학번 NUMBER,
		이름 VARCHAR2(5),
		주민번호 CHAR(14)
	);
	
--테이블 삭제
--DROP TABLE TEST01;

--[실습] 학번 컬럼을 SNUM으로 명칭 변경
--      이름 컬럼을 SNAME으로 명칭 변경
--      주민번호 컬럼 --> JUMIN으로 명칭 변경

ALTER TABLE TEST01 RENAME COLUMN 학번 TO SNUM;
ALTER TABLE TEST01 RENAME COLUMN 이름 TO SNAME;
ALTER TABLE TEST01 RENAME COLUMN 주민번호 TO JUMIN;

--[실습] 학번 컬럼의 타입(NUMBER)를 가변문자형 10으로 수정하기
--      이름을 가변길이 10으로 수정
--      주민번호를 고정길이 10으로 수정
--컬럼의 타입을 변경

ALTER TABLE TEST01 MODIFY SNUM VARCHAR2(10);
ALTER TABLE TEST01 MODIFY SNAME VARCHAR2(10);
ALTER TABLE TEST01 MODIFY JUMIN CHAR(10);


--[실습] 새로운 컬럼 SUBJECT를 가변문자형 10으로 추가하기
ALTER TABLE TEST01 ADD SUBJECT VARCHAR2(10);


--[실습] 특정 컬럼 지우기 : 주민번호(JUMIN)을 삭제하기
ALTER TABLE TEST01 DROP COLUMN JUMIN;

--테이블 이름을 TEST01에서 SCHOOL로 변경하기
ALTER TABLE TEST01 RENAME TO SCHOOL;

--테이블에 GRADE 컬럼을 고정형(3)으로 추가해 보자
ALTER TABLE SCHOOL ADD GRADE CHAR(3);

--테이블 구조 조회해 보자 SELECT * FROM SCHOOL <--- 테이블의 데이터를 조회
--구조를 조회 <- DESC SCHOOL

CREATE TABLE CAR(
		ID NUMBER,
		BRAND VARCHAR2(20),
		COLOR VARCHAR2(20),
		PRICE NUMBER(10),
		--제약조건 : CONSTRAINT
		--id라는 컬럼에 기본키(PK)를 걸거야 이때, 그 키값을 관리하는
		--이름으로 PK_CAR 라고 지을 거야...
		CONSTRAINT pk_car PRIMARY KEY(id) 

	);
-- PK_CAR 삭제하기 : ALTER
ALTER TABLE CAR DROP CONSTRAINT PKK_CAR; 

--추가 : ID를 기본키로 추가하고 싶다
--ALTER TABLE CAR ADD CONSTRAINT 이름 키조건(컬럼명);
ALTER TABLE CAR ADD CONSTRAINT PKK_CAR PRIMARY KEY(ID);

DROP TABLE ANIMAL;

--애니멀 테이블 생성 (제약조건을 컬럼에 바로 붙인다)
CREATE TABLE ANIMAL(
		ID NUMBER PRIMARY KEY, --관리하는 이름이 없으니까... 수정 삭제시 불편하다!
		TYPE VARCHAR2(10),
		AGE NUMBER(2),
		FEED VARCHAR2(10)
	);

DROP TABLE ANIMAL;

CREATE TABLE ANIMAL(
		ID NUMBER,
		ANI_TYPE VARCHAR2(10),
		AGE NUMBER(2),
		FEED VARCHAR2(10)
	);
--제약조건 수정하기
ALTER TABLE ANIMAL ADD CONSTRAINT ANI PRIMARY KEY(ID);

ALTER TABLE ANIMAL DROP CONSTRAINT ANI;
--데이터 삽입
INSERT INTO animal  (id, ani_type, age, feed)
			values(1, 'puppy', 3, '잡식');

--데이터 조회
SELECT * FROM ANIMAL;

-- 3개 정도 INSERT 해보기
--INSERT 문을 한줄에 하면 다 실행 가능하다
INSERT INTO ANIMAL (ID, ANI_TYPE, AGE, FEED)
			VALUES(2, 'cat', 23, 'mouse');
INSERT INTO ANIMAL (ID, ANI_TYPE, AGE, FEED)
			VALUES(3, 'horse', 17, 'carrot');
INSERT INTO ANIMAL (ID, ANI_TYPE, AGE, FEED)
			VALUES(4, 'elephant', 12, 'banana');

--테이블에 있는 데이터 삭제하기 (한꺼번에 다) DML < DDL
--										   delete < truncate
--													 속도가 더 빠르다!

TRUNCATE TABLE ANIMAL ;

CREATE TABLE STUDENT(
		ID NUMBER(10),
		NAME VARCHAR2(15),
		MAJOR VARCHAR2(20),
		GENDER CHAR(1) DEFAULT 'F' NOT NULL --INSERT 값이 안나오면 무조건 여자로 잡는다!공백이 있으면 안된다!
		       CONSTRAINT BAN_CHAR
	       		CHECK(GENDER IN('M','F')), 
		BIRTH DATE
              		CONSTRAINT BAN_DATE
	      		CHECK(BIRTH >= TO_DATE('1980-01-01', 'YYYY-MM-DD')), --문자열을 날짜로 바꿔주는 함수
		CONSTRAINT PK_STD PRIMARY KEY(ID)
	);

DROP TABLE STUDENT ;

INSERT INTO STUDENT (ID, NAME, MAJOR, BIRTH) 
	VALUES(1, '김세현', 'IT', TO_DATE('1994-10-02', 'YYYY-MM-DD'));
	
SELECT * FROM STUDENT;

--강사PC (192.168.2.254)에 데이터 올리기
INSERT INTO STUDENT (ID, NAME, MAJOR, GENDER ,BIRTH) 
	VALUES(5125, '백성민', 'IT', 'M', TO_DATE('1984-09-10', 'YYYY-MM-DD'));

TRUNCATE TABLE STUDENT;
--ALTER TABLE SCOTT.STUDENT MODIFY GENDER CHAR(2) DEFAULT 'F' ;

CREATE TABLE REPORTCARD(
	ID NUMBER(10),
	FIRST_NAME VARCHAR2(10),
	LAST_NAME VARCHAR2(10),
	SUBJECT VARCHAR2(20),
	GRADE CHAR(3) DEFAULT 'N/A' UNIQUE 
			CONSTRAINT GRADE_CHAR
			CHECK(GRADE IN('N/A', 'A+','A','A-','B+','B','B-','C+','C','C-','D','F')),
	GENDER CHAR(1) DEFAULT 'M' NOT NULL 
			CONSTRAINT GENDER_CHAR
			CHECK(GENDER IN('M','F')),
	DOB DATE,
	CONSTRAINT PK_ID PRIMARY KEY(ID)
	);
DROP TABLE REPORTCARD;
--데이터 조회
SELECT * FROM REPORTCARD;

--제약조건 수정하기
ALTER TABLE REPORTCARD ADD CONSTRAINT PK_ID PRIMARY KEY(ID);

--전체 블럭을 지정하고 일괄 실행하고 싶으면 alt + X를 누름
--데이터 삽입
INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, DOB )
	VALUES(21, 'JOHN', 'LENNON','MATH', TO_DATE('1942-07-09', 'YYYY-MM-DD'));


INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, DOB) 
	VALUES(1, 'JOHN', 'PETRUCCI','MATH', '1977-04-23'); 

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GRADE, DOB)
	VALUES(2, 'STEVE', 'VAI','ENGLISH', 'A-', '1968-02-03');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GRADE, DOB)
	VALUES(3, 'AL', 'DI MEOLA','ENGLISH', 'B+', '1954-07-26');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GRADE, DOB)
	VALUES(4, 'CHICK', 'COREA','ENGLISH', 'A+', '1947-11-13');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GRADE, DOB)
	VALUES(5, 'ALBERT', 'KING','ENGLISH', 'C', '1940-12-23');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GRADE, DOB)
	VALUES(6, 'BRIAN', 'BAEK','ENGLISH', 'C+', '1984-09-10');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GRADE, DOB)
	VALUES(7, 'LOGAN', 'LEE','ENGLISH', 'F', '1988-05-12');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GENDER, DOB)
	VALUES(8, 'EMILY', 'REMLER', 'ENGLISH', 'F', '1960-01-22');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GENDER, DOB)
	VALUES(9, 'JENNIFER', 'ANNISTON', 'ENLGIHS', 'F', '1972-11-22');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, DOB)
	VALUES(10, 'BASKIN', 'ROBBINS', 'ENGLISH', '1960-01-22');

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, SUBJECT, GENDER, DOB)
	VALUES(11, 'COURTNEY', 'COX', 'ENGLISH', 'F', '1975-08-13');


--컬럼명 수정
ALTER TABLE REPORTCARD RENAME COLUMN ENGLISH TO SUBJECT; 

--테이블명 수정
ALTER TABLE REPORTCARD RENAME TO GRADE;
SELECT * FROM GRADE;
ALTER TABLE GRADE RENAME TO REPORTCARD;
SELECT * FROM REPORTCARD;

--원하는 컬럼 삭제
ALTER TABLE REPORTCARD DROP COLUMN SUBJECT;

--컬럼 구조 변경
ALTER TABLE REPORTCARD MODIFY FIRST_NAME VARCHAR2(10);
ALTER TABLE REPORTCARD MODIFY GRADE VARCHAR2(3); --데이터가 비어있어야 컬럼구조를 변경할 수 있다!
ALTER TABLE REPORTCARD MODIFY SCORE NUMBER(4,2);
ALTER TABLE REPORTCARD MODIFY FIRST_NAME VARCHAR2(2000);

--컬럼 추가
ALTER TABLE REPORTCARD ADD HOMETOWN VARCHAR2(10);
ALTER TABLE REPORTCARD ADD MAJOR VARCHAR2(20);
ALTER TABLE REPORTCARD ADD SCORE NUMBER(2,2);

--컬럼 삭제
ALTER TABLE REPORTCARD DROP COLUMN HOMETOWN;
ALTER TABLE REPORTCARD DROP COLUMN MAJOR;

--테이블 삭제
DROP TABLE REPORTCARD;
--테이블 삭제 및 하위 제약조건도 삭제
DROP TABLE REPORTCARD CASCADE CONSTRAINTS;
--데이터 삭제
TRUNCATE TABLE REPORTCARD;

SELECT * FROM REPORTCARD;

INSERT INTO REPORTCARD (ID, FIRST_NAME, LAST_NAME, DOB, HOMETOWN, MAJOR, SCORE)
VALUES (23, 'JASON', 'BORNE', '1998-09-09', 'DELAWARE', 'HOCKEY', 87.32);

INSERT INTO REPORTCARD (ID, FIRST_NAME , LAST_NAME , DOB, HOMETOWN, MAJOR, SCORE)
VALUES (33, 'JUNO GUILLERMO SANS MARIANO DELAZZI', 'MARTINO', '1997-11-12', 'BOSTON', 'WESTERN ART', 99.99);

DELETE FROM REPORTCARD WHERE ID = 23;
DELETE FROM REPORTCARD WHERE FIRST_NAME = 'LOGAN';
DELETE FROM REPORTCARD WHERE GENDER = 'M';
DELETE FROM REPORTCARD WHERE LAST_NAME = 'MARTINO';

--데이터 수정하기
UPDATE REPORTCARD SET GRADE = 'B-' WHERE FIRST_NAME = 'JOHN';
UPDATE REPORTCARD SET GRADE = 'A+' WHERE LAST_NAME = 'REMLER';
UPDATE REPORTCARD SET HOMETOWN = 'NEW YORK' WHERE LAST_NAME = 'VAI';
UPDATE REPORTCARD SET HOMETOWN = 'NEW JERSEY', MAJOR = 'GUITAR PERFORMANCE' WHERE DOB = '1954-07-26';
UPDATE REPORTCARD SET HOMETOWN = 'SEOUL', MAJOR = 'COMPUTER SCIENCE' WHERE FIRST_NAME = 'BRIAN';
UPDATE REPORTCARD SET GRADE = 'A-', SCORE = 92.45 WHERE FIRST_NAME = 'EMILY';
UPDATE REPORTCARD SET GRADE = 'A+', SCORE = 98.34 WHERE LAST_NAME = 'COX';
UPDATE REPORTCARD SET LAST_NAME = 'GARNER', GRADE = 'B+', SCORE = 87.06 WHERE FIRST_NAME = 'JENNIFER';
ROLLBACK;