--day03
--요구사항
--
--	FLOWER 테이블 생성
--	컬럼명 : NAME, AGE, COLOR
--	FLOWER 에서 FLOWER2 로 변경
--	FLOWER2에서 PRICE컬럼을 추가한다.
--	INSERT로 값 넣기 (2행)
--	FLOWER2 테이블 값들 삭제
--	FLOWER2 테이블 삭제

CREATE TABLE FLOWER(
		NAME VARCHAR2(10),
		AGE NUMBER,
		COLOR CHAR(10) 
	);
	--테이블 확인
	SELECT * FROM TAB;
	--테이블명 변경
	ALTER TABLE FLOWER RENAME TO FLOWER2;

	SELECT * FROM FLOWER2;

	ALTER TABLE FLOWER2 ADD PRICE NUMBER(5);

	ALTER TABLE FLOWER2 MODIFY AGE NUMBER(2);
	ALTER TABLE FLOWER2 MODIFY COLOR VARCHAR2(10);

	INSERT INTO FLOWER2(NAME, AGE, COLOR, PRICE) VALUES('ROSE', 12, 'VELVET', 10000);
	INSERT INTO FLOWER2(NAME, AGE, COLOR, PRICE) VALUES('LILY', 2, 'ORANGE', 5000);
	
	--INSERT INTO FLOWER2(AGE, NAME, COLOR, PRICE) VALUES('LILY', 2, 'ORANGE', 5000); --순서가 바꿔도 바뀐 순서대로 데이터를 집어넣으면 된다!
	INSERT INTO FLOWER2 VALUES ('SUNFLOWER', 3, 'YELLOW', 4000); --중간에 변수명을 생략해도 된다
	

	TRUNCATE TABLE FLOWER2;

	DROP TABLE FLOWER2;
--------------------------------------------------------------------------------------------------------------------
--테이블의 구조
SELECT * FROM DEPT;

SELECT * FROM EMP;

--외래키 제약조건으로 만들기 : EMP2 테이블

	CREATE TABLE EMP2(
		EMPNO NUMBER(4,0),
		JOB VARCHAR2(9),
		SAL NUMBER(7,2),
		DEPTNO NUMBER(2,0),  --DEPT.DEPTNO의 조건과 동일
		--제약조건
		CONSTRAINT FK_DEPTNO2 FOREIGN KEY(DEPTNO)
			REFERENCES DEPT(DEPTNO), --DEPT 참조대상 테이블, DEPTNO 참조대상 컬럼명
		CONSTRAINT PK_EMPNO PRIMARY KEY(EMPNO)
		--부모인 DEPT에 걸어주는게 좋다
	);

--create 할 때 생성했던 외래키(foreign key) 삭제
	ALTER TABLE EMP2 DROP CONSTRAINT FK_DEPTNO2;	

	--새로운 외래키를 추가해 보자 (FK_DEPTNO3)
	ALTER TABLE EMP2 ADD CONSTRAINT FK_DEPTNO3
			FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO);

--꽃과 화분

		CREATE TABLE BUYER(
			ID VARCHAR2(20),
			NAME VARCHAR2(20),
			ADDRESS VARCHAR2(30),
			EMAIL VARCHAR2(20) NOT NULL,
			CONSTRAINT PK_MEMBER_ID PRIMARY KEY(ID),
			CONSTRAINT PK_EMAIL UNIQUE(EMAIL)
		);
	
		CREATE TABLE FLOWER(
			FNAME VARCHAR2(20),
			FCOLOR VARCHAR2(10),
			PRICE NUMBER(10),
			CONSTRAINT PK_FNAME PRIMARY KEY(FNAME)
		);
	
		CREATE TABLE FPOT(
			PRODUCT_NUMBER NUMBER(5),
			PCOLOR VARCHAR2(20),
			PSHAPE VARCHAR2(10),
			FNAME VARCHAR2(20),
			CONSTRAINT FK_FNAME_FPOT FOREIGN KEY(FNAME) REFERENCES FLOWER(FNAME),
			CONSTRAINT PK_PRODUCT_NUMBER PRIMARY KEY(PRODUCT_NUMBER) 
		);
	
		CREATE TABLE PURCHASE(
			ID VARCHAR2(20),
			ORDER_NUMBER NUMBER(5),
			PRODUCT_NUMBER NUMBER(5),
			FNAME VARCHAR2(20),
			ADDRESS VARCHAR2(30),
			CONSTRAINT FK_PURCHASE_ID FOREIGN KEY(ID)
				REFERENCES BUYER(ID),
			CONSTRAINT FK_PRODUCT_NUMBER FOREIGN KEY(PRODUCT_NUMBER)
				REFERENCES FPOT(PRODUCT_NUMBER),
			CONSTRAINT FK_FNAME_PURCHASE FOREIGN KEY(FNAME)
				REFERENCES FLOWER(FNAME),
			CONSTRAINT PK_ORDER_NUMBER PRIMARY KEY(ORDER_NUMBER)
		); 

ALTER TABLE MEMBER RENAME TO BUYER; 
ALTER TABLE BUYER MODIFY EMAIL VARCHAR2(30);	

INSERT INTO BUYER VALUES('840910-1042014', 'BRIAN', 'SEOUL, KOREA', 'koreanbradpitt@gmail.com');
INSERT INTO BUYER VALUES('570203-2030324', 'LAKE', 'SEOUL, KOREA', 'lakehae@gmail.com');

SELECT * FROM BUYER;

INSERT INTO FLOWER VALUES('ROSE', 'WHITE', 5000);
INSERT INTO FLOWER VALUES('LILY', 'YELLOW', 6000);
INSERT INTO FLOWER VALUES('TULIP', 'PURPLE', 7000);
	
SELECT * FROM FLOWER;

INSERT INTO FPOT VALUES('23198', 'BROWN', 'SQUARE', 'ROSE');
INSERT INTO FPOT VALUES('23199', 'BLUE', 'TRIANGLE', 'LILY');
INSERT INTO FPOT VALUES('23200', 'GREEN', 'RECTANGLE', 'TULIP');

SELECT * FROM FPOT; 

INSERT INTO PURCHASE VALUES('840910-1042014', '2319', '23200', 'TULIP', 'SEOUL, KOREA');
INSERT INTO PURCHASE VALUES('570203-2030324', '2320', '23200', 'TULIP', 'TOKYO, JAPAN');

SELECT * FROM PURCHASE;

TRUNCATE TABLE FLOWER;
TRUNCATE TABLE FPOT;
TRUNCATE TABLE PURCHASE;

DROP TABLE PURCHASE;	
DROP TABLE FLOWER;
DROP TABLE BUYER;
DROP TABLE FPOT;

	
























